stages:
  - "build"
  - "test"
  - "release"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_INDEX_URL: "http://mirrors.cloud.aliyuncs.com/pypi/simple/"
  PIP_TRUSTED_HOST: "mirrors.cloud.aliyuncs.com"



build-job:
  image: python:latest
  stage: build
  cache:
    key: build-cache
    paths:
      - .cache/pip
      - venv/
  script:
    - "env"
    - "pip3 install --upgrade build wheel setuptools"
    - "python3 setup.py bdist_wheel"
  artifacts:
    paths:
    - dist
    expire_in: 1 week

test-py36:
  image: python:3.6
  stage: test
  cache:
    key: test-cache-36
    paths:
      - .cache/pip
      - venv/
  script:
    - "pip3 install --upgrade -r requirements.txt"
    - "pip3 install --upgrade -r requirements-dev.txt"
    - "pip3 install torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run_test.py"

test-py37:
  image: python:3.7
  stage: test
  cache:
    key: test-cache-37
    paths:
      - .cache/pip
      - venv/
  script:
    - "pip3 install --upgrade -r requirements.txt"
    - "pip3 install --upgrade -r requirements-dev.txt"
    - "pip3 install torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run_test.py"

test-py38:
  image: python:3.8
  stage: test
  cache:
    key: test-cache-38
    paths:
      - .cache/pip
      - venv/
  script:
    - "pip3 install --upgrade -r requirements.txt"
    - "pip3 install --upgrade -r requirements-dev.txt"
    - "pip3 install torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run_test.py"

test-py39:
  image: python:3.9
  stage: test
  cache:
    key: test-cache-39
    paths:
      - .cache/pip
      - venv/
  script:
    - "pip3 install --upgrade -r requirements.txt"
    - "pip3 install --upgrade -r requirements-dev.txt"
    - "pip3 install torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run_test.py"

release-step:
  image: python:latest
  stage: release
  cache:
    key: release-cache
    paths:
      - .cache/pip
      - venv/
  script:
    - "pip3 install --upgrade twine"
    - "python3 -m twine upload dist/*"
  only:
    - tags
  except:
    - branches
