stages:
  - "build"
  - "test"
  - "release"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

build-job:
  image: python:latest
  stage: build
  script:
    - "pip3 install --upgrade build wheel setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - 'python3 -m build'
  artifacts:
    paths:
    - dist
    expire_in: 1 week

test-py36:
  image: python:3.6
  stage: test
  script:
    - "pip3 install --upgrade -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - "pip3 install --upgrade -r requirements-dev.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run.py"

test-py37:
  image: python:3.7
  stage: test
  script:
    - "pip3 install --upgrade -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - "pip3 install --upgrade -r requirements-dev.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run.py"

test-py38:
  image: python:3.8
  stage: test
  script:
    - "pip3 install --upgrade -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - "pip3 install --upgrade -r requirements-dev.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run.py"

test-py39:
  image: python:3.9
  stage: test
  script:
    - "pip3 install --upgrade -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - "pip3 install --upgrade -r requirements-dev.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - 'pip3 install $(find dist -name "*.whl")'
    - "python3 tests/run.py"

release-step:
  image: python:latest
  stage: release
  script:
    - "pip3 install --upgrade twine -i https://pypi.tuna.tsinghua.edu.cn/simple/"
    - "python3 -m twine upload dist/*"
  only:
    - tags
  except:
    - branches
