# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kara_storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kara_storage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12kara_storage.proto\"6\n\x0bKaraRequest\x12\n\n\x02op\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05\x66name\x18\x03 \x01(\t\"*\n\x0cKaraResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xc0\x01\n\x0bKaraGateway\x12\x30\n\rStreamDataset\x12\x0c.KaraRequest\x1a\r.KaraResponse(\x01\x30\x01\x12/\n\x0cStreamObject\x12\x0c.KaraRequest\x1a\r.KaraResponse(\x01\x30\x01\x12&\n\x07GetMeta\x12\x0c.KaraRequest\x1a\r.KaraResponse\x12&\n\x07PutMeta\x12\x0c.KaraRequest\x1a\r.KaraResponseb\x06proto3'
)




_KARAREQUEST = _descriptor.Descriptor(
  name='KaraRequest',
  full_name='KaraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='KaraRequest.op', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='KaraRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fname', full_name='KaraRequest.fname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=76,
)


_KARARESPONSE = _descriptor.Descriptor(
  name='KaraResponse',
  full_name='KaraResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='KaraResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='KaraResponse.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['KaraRequest'] = _KARAREQUEST
DESCRIPTOR.message_types_by_name['KaraResponse'] = _KARARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KaraRequest = _reflection.GeneratedProtocolMessageType('KaraRequest', (_message.Message,), {
  'DESCRIPTOR' : _KARAREQUEST,
  '__module__' : 'kara_storage_pb2'
  # @@protoc_insertion_point(class_scope:KaraRequest)
  })
_sym_db.RegisterMessage(KaraRequest)

KaraResponse = _reflection.GeneratedProtocolMessageType('KaraResponse', (_message.Message,), {
  'DESCRIPTOR' : _KARARESPONSE,
  '__module__' : 'kara_storage_pb2'
  # @@protoc_insertion_point(class_scope:KaraResponse)
  })
_sym_db.RegisterMessage(KaraResponse)



_KARAGATEWAY = _descriptor.ServiceDescriptor(
  name='KaraGateway',
  full_name='KaraGateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=315,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamDataset',
    full_name='KaraGateway.StreamDataset',
    index=0,
    containing_service=None,
    input_type=_KARAREQUEST,
    output_type=_KARARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamObject',
    full_name='KaraGateway.StreamObject',
    index=1,
    containing_service=None,
    input_type=_KARAREQUEST,
    output_type=_KARARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMeta',
    full_name='KaraGateway.GetMeta',
    index=2,
    containing_service=None,
    input_type=_KARAREQUEST,
    output_type=_KARARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutMeta',
    full_name='KaraGateway.PutMeta',
    index=3,
    containing_service=None,
    input_type=_KARAREQUEST,
    output_type=_KARARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KARAGATEWAY)

DESCRIPTOR.services_by_name['KaraGateway'] = _KARAGATEWAY

# @@protoc_insertion_point(module_scope)
