KARA_OP_OPEN_DS = 1
KARA_OP_CLOSE_DS = 2
KARA_OP_CLOSED_DS = 3
KARA_OP_FLUSH_DS = 4
KARA_OP_WRITE_DS = 5
KARA_OP_READ_DS = 6
KARA_OP_SEEK_DS = 7
KARA_OP_PREAD_DS = 8
KARA_OP_SIZE_DS = 9
KARA_OP_TELL_DS = 10

KARA_OP_STORAGE_OBJ = 11
KARA_OP_HAS_FILE_OBJ = 12
KARA_OP_READ_OBJ = 13
KARA_OP_UPLOAD_OBJ = 14
KARA_OP_FINISH_UPLOAD_OBJ = 15
KARA_OP_GET_VER_OBJ = 16
KARA_OP_SET_VER_OBJ = 17